name: Production deploy pipeline

on:
  push:
    branches:
      - main

jobs:
  production-deploy:
    runs-on: ubuntu-latest
    environment: staging
    env:
      REGISTRY_NAME: ${{ vars.REGISTRY_NAME }}
      GCP_PROJECT: ${{ vars.GCP_PROJECT }}
      GCP_APPLICATION: ${{ vars.GCP_APPLICATION }}
      GCP_REPOSITORY: ${{ vars.GCP_REPOSITORY }}
      GCP_REGION: ${{ vars.GCP_REGION }}
    steps:
      - uses: actions/checkout@v4
      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.GCP_CREDENTIALS }}"
      - name: "Cleanup staging environment"
        run: |
          ./scripts/gh_actions/delete-image.sh
          ./scripts/gh_actions/delete-service.sh
