name: Staging deploy pipeline

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened

jobs:
  code_standards:
    uses: ./.github/workflows/code_standards.yml
  staging-deploy:
    runs-on: ubuntu-latest
    environment: staging
    needs: [code_standards]
    env:
      REGISTRY_NAME: ${{ vars.REGISTRY_NAME }}
      GCP_PROJECT: ${{ vars.GCP_PROJECT }}
      GCP_APPLICATION: ${{ vars.GCP_APPLICATION }}
      GCP_REPOSITORY: ${{ vars.GCP_REPOSITORY }}
      GCP_REGION: ${{ vars.GCP_REGION }}
    steps:
      - uses: actions/checkout@v4
      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.GCP_CREDENTIALS }}"
      - name: "Publishing image"
        run: |
          gcloud auth configure-docker "${{ env.REGISTRY_NAME }}"
          ./scripts/gh_actions/publish-image.sh
      - name: "Deploy image to staging"
        run: |
          gcloud config set run/region "${{ env.GCP_REGION }}"
          ./scripts/gh_actions/deploy-image.sh
